spring:
  config:
    activate:
      on-profile: "local"
  profiles:
    include:
      - "core-local"
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/pullout
    username: root
    password: 43214321

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      jdbc:
        lob:
          non_contextual_creation: true
      hibernate:
        format_sql: true
        use_sql_comments: true
        naming:
          physical-strategy = org.hibernate.model.naming.PhysicalNamingStrategyStandardImpl
    database: mysql

# Logging Info
logging:
  level:
    org.springframework: debug