spring:
  config:
    activate:
      on-profile: "local"
  ## DataBase (H2)
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://mariadb-container:3306/pullout
    username: root
    password: 43214321

  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        naming:
          physical-strategy = org.hibernate.model.naming.PhysicalNamingStrategyStandardImpl
    database: mysql
    generate-ddl: true