spring:
  config:
    activate:
      on-profile: "local"

  flyway:
    enabled: true
    url: jdbc:mariadb://localhost:3306/pullout
    user: root
    password: 43214321
    baseline-on-migrate: true
